git:
    remote: https://github.com/HackGT/ballot.git
    branch: master
    
secrets:
    - SESSION_SECRET
    - AUTH_GITHUB_ID
    - AUTH_GITHUB_SECRET
    - AUTH_FACEBOOK_ID
    - AUTH_FACEBOOK_SECRET
    - AUTH_GOOGLE_ID
    - AUTH_GOOGLE_SECRET

wants:
    postgres: true

env:
    NODE_ENV: production
    AUTH_ALLOW_LOCAL: true
