export const INCREMENT_NUMBER = 'INCREMENT_NUMBER';
export type INCREMENT_NUMBER = typeof INCREMENT_NUMBER;

export const DECREMENT_NUMBER = 'DECREMENT_NUMBER';
export type DECREMENT_NUMBER = typeof DECREMENT_NUMBER;